baseURL = 'https://guemax.de/'
languageCode = 'de-de'
title = 'Max Günther'
theme = 'zapf'

[params]

homeIntroContent = """Herzlich willkommen!  In diesem Blog
veröffentliche ich Artikel zu Themen wie Programmieren, Schriftsatz
und vielem mehr.  Meine Soft- und Hardwareprojekte rund um Rust,
Python und (La)TeX finden Sie auf [GitHub](https://github.com/guemax)
und [Codeberg](https://codeberg.org/guemax).

Bei Fragen, Anregungen und Kritik zu diesem Blog kontaktieren Sie mich
bitte per E-Mail: [info@guemax.de](mailto:info@guemax.de)."""

homeCollectionTitle = 'Blog'
homeCollection = 'blog'

paginationSize = 100

[markup]
[markup.highlight]
style = 'algol'
